# ANIVIA GAME INSIGHT

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
import warnings
warnings.filterwarnings("ignore")

## Veri Hazırlama

### Steam Değişken Düzenleme

In [3]:
df_steam = pd.read_csv("web-scraping-data/steam.csv")
df_steam.head()

,oyun_adi,etiketler,gelistirici,yayinci,yayin_tarihi,turkce_incelemeler,en_son_incelemeler,turkce_destegi,fiyat_dlc,fiyat2,ozellikler,kontrolcu_destegi,dil_sayisi,diller_detay,yas_siniri
0,EA SPORTS FC™ 26,"Futbol, Spor, Simülasyon, Çok Oyunculu, Tek Oy...","EA Canada, EA Romania",Electronic Arts,25 Eyl 2025,"Türkçe İncelemelerKarışık(%49/5,840)","En Son:Karışık(%47/4,600)","Arayuz, Seslendirme, Altyazi",$0.99 USD,$0.99 USD,"Tek Oyunculu, Çevrimiçi PvP, Ortak/Bölünmüş Ek...",Tam kontrolcu destegi,Türkçe ve 20 dil daha,"Türkçe: Arayuz, Seslendirme, Altyazi | İngiliz...",3+
1,Cities: Skylines,"Şehir Kurma, Simülasyon, İnşa Etme, Yönetim, S...",Colossal Order,Paradox Interactive,10 Mar 2015,"Türkçe İncelemelerÇok Olumlu(%92/8,378)","En Son:Çok Olumlu(%87/1,746)",Desteklenmiyor,$9.49 USD,$20.99 USD,"Tek Oyunculu, Steam Başarımları, Steam Koleksi...",NaN,10 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Al...",3+
2,Grand Theft Auto V Enhanced,"Açık Dünya, Aksiyon, Cinsel İçerik, Çok Oyuncu...",Rockstar North,Rockstar Games,4 Mar 2025,"Türkçe İncelemelerÇok Olumlu(%85/5,837)","En Son:Çok Olumlu(%89/8,219)",Desteklenmiyor,NaN,$29.99 USD,"Tek Oyunculu, Çevrimiçi PvP, Çevrimiçi Eşli, S...",Kismi kontrolcu destegi,13 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",18+
3,Black Desert,"Sandbox, Keşif, Aksiyon RYO, Devasa Çok Oyuncu...",Pearl Abyss,Pearl Abyss,16 May 2018,"Türkçe İncelemelerÇoğunlukla Olumlu(%76/2,652)",En Son:Karışık(%65/385),"Arayuz, Altyazi",$4.99 USD,$4.99 USD,"MMO, Çevrimiçi PvP, Çevrimiçi Eşli, Steam Kole...",Kismi kontrolcu destegi,Türkçe ve 10 dil daha,"Türkçe: Arayuz, Altyazi | İngilizce: Arayuz, S...",16+
4,R.E.P.O.,"Korku, Çevrimiçi Eşli Oyun, Çok Oyunculu, Kome...",semiwork,semiwork,26 Şub 2025,"Türkçe İncelemelerSon Derece Olumlu(%95/8,217)","En Son:Son Derece Olumlu(%95/8,125)",Desteklenmiyor,NaN,$3.49 USD,"Tek Oyunculu, Çevrimiçi Eşli, Steam Cloud, Ail...",NaN,1 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",NaN

In [4]:
df_steam.rename(columns={"etiketler": "oyun_turu"}, inplace=True)
df_steam.head()

,oyun_adi,oyun_turu,gelistirici,yayinci,yayin_tarihi,turkce_incelemeler,en_son_incelemeler,turkce_destegi,fiyat_dlc,fiyat2,ozellikler,kontrolcu_destegi,dil_sayisi,diller_detay,yas_siniri
0,EA SPORTS FC™ 26,"Futbol, Spor, Simülasyon, Çok Oyunculu, Tek Oy...","EA Canada, EA Romania",Electronic Arts,25 Eyl 2025,"Türkçe İncelemelerKarışık(%49/5,840)","En Son:Karışık(%47/4,600)","Arayuz, Seslendirme, Altyazi",$0.99 USD,$0.99 USD,"Tek Oyunculu, Çevrimiçi PvP, Ortak/Bölünmüş Ek...",Tam kontrolcu destegi,Türkçe ve 20 dil daha,"Türkçe: Arayuz, Seslendirme, Altyazi | İngiliz...",3+
1,Cities: Skylines,"Şehir Kurma, Simülasyon, İnşa Etme, Yönetim, S...",Colossal Order,Paradox Interactive,10 Mar 2015,"Türkçe İncelemelerÇok Olumlu(%92/8,378)","En Son:Çok Olumlu(%87/1,746)",Desteklenmiyor,$9.49 USD,$20.99 USD,"Tek Oyunculu, Steam Başarımları, Steam Koleksi...",NaN,10 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Al...",3+
2,Grand Theft Auto V Enhanced,"Açık Dünya, Aksiyon, Cinsel İçerik, Çok Oyuncu...",Rockstar North,Rockstar Games,4 Mar 2025,"Türkçe İncelemelerÇok Olumlu(%85/5,837)","En Son:Çok Olumlu(%89/8,219)",Desteklenmiyor,NaN,$29.99 USD,"Tek Oyunculu, Çevrimiçi PvP, Çevrimiçi Eşli, S...",Kismi kontrolcu destegi,13 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",18+
3,Black Desert,"Sandbox, Keşif, Aksiyon RYO, Devasa Çok Oyuncu...",Pearl Abyss,Pearl Abyss,16 May 2018,"Türkçe İncelemelerÇoğunlukla Olumlu(%76/2,652)",En Son:Karışık(%65/385),"Arayuz, Altyazi",$4.99 USD,$4.99 USD,"MMO, Çevrimiçi PvP, Çevrimiçi Eşli, Steam Kole...",Kismi kontrolcu destegi,Türkçe ve 10 dil daha,"Türkçe: Arayuz, Altyazi | İngilizce: Arayuz, S...",16+
4,R.E.P.O.,"Korku, Çevrimiçi Eşli Oyun, Çok Oyunculu, Kome...",semiwork,semiwork,26 Şub 2025,"Türkçe İncelemelerSon Derece Olumlu(%95/8,217)","En Son:Son Derece Olumlu(%95/8,125)",Desteklenmiyor,NaN,$3.49 USD,"Tek Oyunculu, Çevrimiçi Eşli, Steam Cloud, Ail...",NaN,1 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",NaN

In [5]:
df_steam.info()

<class 'pandas.DataFrame'>
RangeIndex: 4083 entries, 0 to 4082
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   oyun_adi            4083 non-null   str
 1   oyun_turu           4083 non-null   str
 2   gelistirici         4082 non-null   str
 3   yayinci             3922 non-null   str
 4   yayin_tarihi        4083 non-null   str
 5   turkce_incelemeler  225 non-null    str
 6   en_son_incelemeler  975 non-null    str
 7   turkce_destegi      3965 non-null   str
 8   fiyat_dlc           938 non-null    str
 9   fiyat2              4082 non-null   str
 10  ozellikler          4011 non-null   str
 11  kontrolcu_destegi   2139 non-null   str
 12  dil_sayisi          3965 non-null   str
 13  diller_detay        3965 non-null   str
 14  yas_siniri          660 non-null    str
dtypes: str(15)
memory usage: 4.7 MB

In [6]:
df_steam.drop(
    columns=["yayinci", "yayin_tarihi", "fiyat_dlc", "ozellikler", "kontrolcu_destegi"],
    inplace=True,
    errors="ignore"
)

df_steam.head()

,oyun_adi,oyun_turu,gelistirici,turkce_incelemeler,en_son_incelemeler,turkce_destegi,fiyat2,dil_sayisi,diller_detay,yas_siniri
0,EA SPORTS FC™ 26,"Futbol, Spor, Simülasyon, Çok Oyunculu, Tek Oy...","EA Canada, EA Romania","Türkçe İncelemelerKarışık(%49/5,840)","En Son:Karışık(%47/4,600)","Arayuz, Seslendirme, Altyazi",$0.99 USD,Türkçe ve 20 dil daha,"Türkçe: Arayuz, Seslendirme, Altyazi | İngiliz...",3+
1,Cities: Skylines,"Şehir Kurma, Simülasyon, İnşa Etme, Yönetim, S...",Colossal Order,"Türkçe İncelemelerÇok Olumlu(%92/8,378)","En Son:Çok Olumlu(%87/1,746)",Desteklenmiyor,$20.99 USD,10 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Al...",3+
2,Grand Theft Auto V Enhanced,"Açık Dünya, Aksiyon, Cinsel İçerik, Çok Oyuncu...",Rockstar North,"Türkçe İncelemelerÇok Olumlu(%85/5,837)","En Son:Çok Olumlu(%89/8,219)",Desteklenmiyor,$29.99 USD,13 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",18+
3,Black Desert,"Sandbox, Keşif, Aksiyon RYO, Devasa Çok Oyuncu...",Pearl Abyss,"Türkçe İncelemelerÇoğunlukla Olumlu(%76/2,652)",En Son:Karışık(%65/385),"Arayuz, Altyazi",$4.99 USD,Türkçe ve 10 dil daha,"Türkçe: Arayuz, Altyazi | İngilizce: Arayuz, S...",16+
4,R.E.P.O.,"Korku, Çevrimiçi Eşli Oyun, Çok Oyunculu, Kome...",semiwork,"Türkçe İncelemelerSon Derece Olumlu(%95/8,217)","En Son:Son Derece Olumlu(%95/8,125)",Desteklenmiyor,$3.49 USD,1 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",NaN

In [7]:
len(df_steam[df_steam['turkce_incelemeler'].isna() & df_steam['en_son_incelemeler'].isna()])

3101

In [8]:
len(df_steam[df_steam['turkce_incelemeler'].notna() & df_steam['en_son_incelemeler'].isna()])

7

In [9]:
len(df_steam[df_steam['turkce_incelemeler'].isna() & df_steam['en_son_incelemeler'].notna()])

757

In [10]:
len(df_steam[df_steam['turkce_incelemeler'].notna() & df_steam['en_son_incelemeler'].notna()])

218

In [11]:
df_steam = df_steam[~(df_steam['turkce_incelemeler'].notna() & df_steam['en_son_incelemeler'].isna())]

df_steam.drop(columns=['turkce_incelemeler'], inplace=True)

df_steam.info()

<class 'pandas.DataFrame'>
Index: 4076 entries, 0 to 4082
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   oyun_adi            4076 non-null   str
 1   oyun_turu           4076 non-null   str
 2   gelistirici         4075 non-null   str
 3   en_son_incelemeler  975 non-null    str
 4   turkce_destegi      3958 non-null   str
 5   fiyat2              4075 non-null   str
 6   dil_sayisi          3958 non-null   str
 7   diller_detay        3958 non-null   str
 8   yas_siniri          659 non-null    str
dtypes: str(9)
memory usage: 3.7 MB

In [12]:
df_steam.rename(columns={"en_son_incelemeler": "puan"}, inplace=True)
df_steam.rename(columns={"fiyat2": "fiyat"}, inplace=True)
df_steam.rename(columns={"diller_detay": "dil"}, inplace=True)
df_steam.rename(columns={"yas_siniri": "yas"}, inplace=True)

df_steam.head()

,oyun_adi,oyun_turu,gelistirici,puan,turkce_destegi,fiyat,dil_sayisi,dil,yas
0,EA SPORTS FC™ 26,"Futbol, Spor, Simülasyon, Çok Oyunculu, Tek Oy...","EA Canada, EA Romania","En Son:Karışık(%47/4,600)","Arayuz, Seslendirme, Altyazi",$0.99 USD,Türkçe ve 20 dil daha,"Türkçe: Arayuz, Seslendirme, Altyazi | İngiliz...",3+
1,Cities: Skylines,"Şehir Kurma, Simülasyon, İnşa Etme, Yönetim, S...",Colossal Order,"En Son:Çok Olumlu(%87/1,746)",Desteklenmiyor,$20.99 USD,10 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Al...",3+
2,Grand Theft Auto V Enhanced,"Açık Dünya, Aksiyon, Cinsel İçerik, Çok Oyuncu...",Rockstar North,"En Son:Çok Olumlu(%89/8,219)",Desteklenmiyor,$29.99 USD,13 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",18+
3,Black Desert,"Sandbox, Keşif, Aksiyon RYO, Devasa Çok Oyuncu...",Pearl Abyss,En Son:Karışık(%65/385),"Arayuz, Altyazi",$4.99 USD,Türkçe ve 10 dil daha,"Türkçe: Arayuz, Altyazi | İngilizce: Arayuz, S...",16+
4,R.E.P.O.,"Korku, Çevrimiçi Eşli Oyun, Çok Oyunculu, Kome...",semiwork,"En Son:Son Derece Olumlu(%95/8,125)",Desteklenmiyor,$3.49 USD,1 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",NaN

In [13]:
df_steam["puan"] = pd.to_numeric(
    df_steam["puan"].str.extract(r"%(\d+)\s*/", expand=False),
    errors="coerce"
)

df_steam.head()

,oyun_adi,oyun_turu,gelistirici,puan,turkce_destegi,fiyat,dil_sayisi,dil,yas
0,EA SPORTS FC™ 26,"Futbol, Spor, Simülasyon, Çok Oyunculu, Tek Oy...","EA Canada, EA Romania",47.0,"Arayuz, Seslendirme, Altyazi",$0.99 USD,Türkçe ve 20 dil daha,"Türkçe: Arayuz, Seslendirme, Altyazi | İngiliz...",3+
1,Cities: Skylines,"Şehir Kurma, Simülasyon, İnşa Etme, Yönetim, S...",Colossal Order,87.0,Desteklenmiyor,$20.99 USD,10 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Al...",3+
2,Grand Theft Auto V Enhanced,"Açık Dünya, Aksiyon, Cinsel İçerik, Çok Oyuncu...",Rockstar North,89.0,Desteklenmiyor,$29.99 USD,13 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",18+
3,Black Desert,"Sandbox, Keşif, Aksiyon RYO, Devasa Çok Oyuncu...",Pearl Abyss,65.0,"Arayuz, Altyazi",$4.99 USD,Türkçe ve 10 dil daha,"Türkçe: Arayuz, Altyazi | İngilizce: Arayuz, S...",16+
4,R.E.P.O.,"Korku, Çevrimiçi Eşli Oyun, Çok Oyunculu, Kome...",semiwork,95.0,Desteklenmiyor,$3.49 USD,1 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",NaN

In [14]:
df_steam['id'] = range(1, len(df_steam) + 1)
df_steam = df_steam[['id'] + [col for col in df_steam.columns if col != 'id']]
df_steam.head()

,id,oyun_adi,oyun_turu,gelistirici,puan,turkce_destegi,fiyat,dil_sayisi,dil,yas
0,1,EA SPORTS FC™ 26,"Futbol, Spor, Simülasyon, Çok Oyunculu, Tek Oy...","EA Canada, EA Romania",47.0,"Arayuz, Seslendirme, Altyazi",$0.99 USD,Türkçe ve 20 dil daha,"Türkçe: Arayuz, Seslendirme, Altyazi | İngiliz...",3+
1,2,Cities: Skylines,"Şehir Kurma, Simülasyon, İnşa Etme, Yönetim, S...",Colossal Order,87.0,Desteklenmiyor,$20.99 USD,10 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Al...",3+
2,3,Grand Theft Auto V Enhanced,"Açık Dünya, Aksiyon, Cinsel İçerik, Çok Oyuncu...",Rockstar North,89.0,Desteklenmiyor,$29.99 USD,13 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",18+
3,4,Black Desert,"Sandbox, Keşif, Aksiyon RYO, Devasa Çok Oyuncu...",Pearl Abyss,65.0,"Arayuz, Altyazi",$4.99 USD,Türkçe ve 10 dil daha,"Türkçe: Arayuz, Altyazi | İngilizce: Arayuz, S...",16+
4,5,R.E.P.O.,"Korku, Çevrimiçi Eşli Oyun, Çok Oyunculu, Kome...",semiwork,95.0,Desteklenmiyor,$3.49 USD,1 dil destekleniyor,"Türkçe: Desteklenmiyor | İngilizce: Arayuz, Se...",NaN

In [15]:
df_steam.info()

<class 'pandas.DataFrame'>
Index: 4076 entries, 0 to 4082
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4076 non-null   int64
 1   oyun_adi        4076 non-null   str
 2   oyun_turu       4076 non-null   str
 3   gelistirici     4075 non-null   str
 4   puan            975 non-null    float64
 5   turkce_destegi  3958 non-null   str
 6   fiyat           4075 non-null   str
 7   dil_sayisi      3958 non-null   str
 8   dil             3958 non-null   str
 9   yas             659 non-null    str
dtypes: float64(1), int64(1), str(8)
memory usage: 3.7 MB

In [ ]:
df_epic= pd.read_csv("web-scraping-data/epicveri1.csv")
df_epic.head()

In [ ]:
df_ps = pd.read_csv("web-scraping-data/PSVERİ1SONHALİ.csv")
df_ps.head()

In [ ]:
df_nintendo = pd.read_csv("web-scraping-data/NINTENDO.csv")
df_nintendo.head()

In [ ]:
df_xbox = pd.read_csv("web-scraping-data/XBOX_TUM_OYUNLAR.csv")
df_xbox.head()