In [1]:
import pandas as pd
import gspread
import toml
import os

In [2]:
# 1. Streamlit şifre kasamızı Jupyter Notebook'ta açıyoruz 
with open("../.streamlit/secrets.toml", "r", encoding="utf-8") as f:
    secrets = toml.load(f)

# 2. Kasadaki bilgilerle Google Cloud'a (GSheets) şifreli giriş yapıyoruz
gc = gspread.service_account_from_dict(secrets["connections"]["gsheets"])

# 3. Tablomuzu ID'si ile bulup canlı açıyoruz
# ID'yi kodun içinden değil, şifre kasasından çekiyoruz
sheet_id = secrets["connections"]["gsheets"]["sheet_id_veli"]
sheet = gc.open_by_key(sheet_id)

# 4. Sayfadaki tüm veriyi çekip anında Pandas DataFrame'ine çeviriyoruz
# Not: get_all_records() hata verebilir (başlıklar benzersiz değilse), bu yüzden get_all_values() kullanıyoruz
data = sheet.sheet1.get_all_values()
df_anket = pd.DataFrame(data[1:], columns=data[0])

print(f"✅ Canlı bağlantı başarılı! Toplam {len(df_anket)} veli verisi anlık olarak çekildi.")
display(df_anket.head())

FileNotFoundError: [Errno 2] No such file or directory: '../.streamlit/secrets.toml'

In [ ]:
# Boş sütunları tespit et ve sil
bos_sutunlar = df_anket.columns[df_anket.replace(r'^\s*$', pd.NA, regex=True).isna().all()]
print(f"Silinecek boş sütun sayısı: {len(bos_sutunlar)}")

df_anket = df_anket.drop(columns=bos_sutunlar)

print(f"Kalan sütun sayısı: {df_anket.shape[1]}")
display(df_anket.head())

Silinecek boş sütun sayısı: 3
Kalan sütun sayısı: 39

,Zaman damgası,Bu anketi kimin adına dolduruyorsunuz?,Cinsiyetiniz?,Yaşınız?,Oyun oynadığınız günlerde (ekran başına geçtiğinizde) genellikle ne kadar süre vakit geçirirsiniz?,Oyun oynamak için EN SIK kullandığınız cihaz hangisidir?,En çok vakit geçirdiğiniz oyun türü hangisidir?,"Oyun içi harcamalara (kutu açma, kostüm, avantaj sağlayan eşyalar vb.) ayda ortalama ne kadar bütçe ayırıyorsunuz?",Oyun içi harcamalarınız bütçenizi ve finansal kontrolünüzü nasıl etkiliyor?,"Rekabetçi bir maçı kaybettiğinizde oyunu bırakma veya ""oynamaya devam etme"" eğiliminiz nasıldır?",...,Oyunu kapattıktan sonra çocuğunuzun gerçek hayattaki ruh halini nasıl gözlemliyorsunuz?,"Çocuğunuzun oynadığı oyunlardaki yaş sınırı etiketlerini (Örn: PEGI 12, PEGI 18) kontrol ediyor musunuz?",Türkiye'de yasal bir temsilcisi bulunmayan oyun platformlarına erişim kısıtlanması uygulanması ihtimalini nasıl değerlendiriyorsunuz?,Sizlere daha iyi bir araştırma sunabilmek için dikkat ölçümü yapıyoruz. \n\nLütfen aşağıdaki seçenekler arasından 'Mavi' rengini işaretleyiniz.,Sizlere daha iyi bir araştırma sunabilmek için dikkat ölçümü yapıyoruz. \n\nLütfen aşağıdaki seçenekler arasından 'Mavi' rengini işaretleyiniz.,"Oyun içinde gerçek parayla harcama YAPIYORSANIZ ""en temel"" amacı genellikle hangisidir?","Çocuğunuz ortalama bir haftada, haftanın kaç günü oyun oynar?","Ortalama bir haftayı düşündüğünüzde, haftanın kaç günü oyun oynarsınız?",18 yaş altı kullanıcılar için oyun içi harcamalara ebeveyn onayı getirmeli midir?,18 yaş altı kullanıcılar için oyun içi harcamalara ebeveyn onayı getirmeli midir?
0,20.05.2026 20:12:33,18 Yaş Üzeriyim - Kendim İçin,Erkek,29-35,1-3 saat,"Kişisel Bilgisayar (Masaüstü, Laptop - Steam, ...","Rekabetçi Nişancı & Battle Royale (Valorant, C...",Hiç harcama yapmam,Hiç harcamam veya sınırlarımı asla aşmam.,Biraz moralim bozulur ama oyuna ara veririm.,...,,,,Mavi,,Oyun içi harcama yapmam.,,Neredeyse her gün / Her gün,,Kesinlikle destekliyorum
1,20.05.2026 20:14:01,18 Yaş Üzeriyim - Kendim İçin,Kadın,18-22,1-3 saat,"Mobil Cihaz (Akıllı Telefon, Tablet)","Strateji & MOBA (League of Legends - LoL, Clas...",250 TL'den az,Hiç harcamam veya sınırlarımı asla aşmam.,Hırslanırım ve mutlaka kazanana kadar peş peşe...,...,,,,Mavi,,"İçeriği belli olan, doğrudan istediğim bir eşy...",,Sıklıkla (Haftada 3-4 kez),,Kesinlikle destekliyorum
2,20.05.2026 20:26:50,18 Yaş Üzeriyim - Kendim İçin,Erkek,18-22,1-3 saat,"Mobil Cihaz (Akıllı Telefon, Tablet)","Basit Eğlence / Bulmaca (Candy Crush, Kelime O...",250 TL'den az,Hiç harcamam veya sınırlarımı asla aşmam.,Sakince oyunu kapatır veya başka bir işe geçerim.,...,,,,Mavi,,Oyun içi harcama yapmam.,,Hiçbir zaman,,Kesinlikle destekliyorum
3,20.05.2026 20:27:17,18 Yaş Üzeriyim - Kendim İçin,Erkek,23-28,1-3 saat,"Kişisel Bilgisayar (Masaüstü, Laptop - Steam, ...","Rekabetçi Nişancı & Battle Royale (Valorant, C...",250 TL'den az,Hiç harcamam veya sınırlarımı asla aşmam.,Sakince oyunu kapatır veya başka bir işe geçerim.,...,,,,Mavi,,Oyunda daha hızlı ilerlemek veya diğer oyuncul...,,Nadiren (Ayda 1-2 kez),,Destekliyorum
4,20.05.2026 20:27:56,18 Yaş Üzeriyim - Kendim İçin,Erkek,18-22,1-3 saat,"Kişisel Bilgisayar (Masaüstü, Laptop - Steam, ...","Basit Eğlence / Bulmaca (Candy Crush, Kelime O...",Hiç harcama yapmam,Bazen limitimi aşarım ama bütçemi sarsmaz.,Sadece kaybımı telafi etmek için bir maç daha ...,...,,,,Mavi,,Oyun içi harcama yapmam.,,Nadiren (Ayda 1-2 kez),,Kesinlikle destekliyorum

In [ ]:
df = df_anket.copy()
df.columns

Index(['Zaman damgası', 'Bu anketi kimin adına dolduruyorsunuz?',
       'Cinsiyetiniz?', ' Yaşınız?',
       'Oyun oynadığınız günlerde (ekran başına geçtiğinizde) genellikle ne kadar süre vakit geçirirsiniz? ',
       'Oyun oynamak için EN SIK kullandığınız cihaz hangisidir?',
       'En çok vakit geçirdiğiniz oyun türü hangisidir?',
       'Oyun içi harcamalara (kutu açma, kostüm, avantaj sağlayan eşyalar vb.) ayda ortalama ne kadar bütçe ayırıyorsunuz?',
       'Oyun içi harcamalarınız bütçenizi ve finansal kontrolünüzü nasıl etkiliyor? ',
       'Rekabetçi bir maçı kaybettiğinizde oyunu bırakma veya "oynamaya devam etme" eğiliminiz nasıldır?',
       'Sizi oyun oynamaya iten EN TEMEL motivasyon nedir?',
       'Oyun oynamak genel stres seviyenizi nasıl etkiler?',
       'Oyun oynamak için normal uyku saatinizden feragat ettiğiniz (uykusuz kaldığınız) ne sıklıkla olur?',
       'Oyundaki mağlubiyetler veya tartışmalar, oyunu kapattıktan sonra gerçek hayattaki ruh halinizi nasıl etkiler?',
       'Oyunlardaki yaş sınırı (PEGI) uyarılarına dikkat eder misiniz?',
       'Türkiye'de yasal bir temsilcisi bulunmayan oyun platformlarına erişim kısıtlanması uygulanması ihtimalini nasıl değerlendiriyorsunuz?',
       'Cinsiyetiniz?', 'Yaşınız?', 'Çocuğunuzun Cinsiyeti?',
       'Çocuğunuzun yaşı?',
       'Çocuğunuzun oyun oynamak için EN SIK kullandığı cihaz hangisidir?',
       'Çocuğunuzun oyun oynadığı cihazlarda herhangi bir "Ebeveyn Denetimi / Filtreleme Yazılımı" veya süre kısıtlaması kullanıyor musunuz?',
       'Çocuğunuzun en çok vakit geçirdiği oyun türü genelde hangisidir?',
       'Çocuğunuz oyun oynadığı günlerde (ekran başına geçtiğinde) genellikle toplam ne kadar süre oyun oynar? ',
       'Çocuğunuzun oyun içi satın alımlar için ayda ortalama ne kadarlık bir harcama yapmasına izin veriyorsunuz (veya kendi harçlığından harcıyor)?',
       'Çocuğunuzun oyun içi harcamaları bütçenizi ve aranızdaki güveni nasıl etkiliyor? ',
       'Çocuğunuza "Oyun süren bitti, cihazı kapat" dediğinizde genellikle nasıl bir tepki veriyor?',
       'Çocuğunuzun oyun oynadığı dönemlerde genel stres ve kaygı seviyesini nasıl gözlemliyorsunuz?  ',
       'Çocuğunuzun oyun oynadığı günlerde uyku düzeninin bozulduğunu veya uykuya dalmakta zorlandığını ne sıklıkla gözlemliyorsunuz?',
       'Oyunu kapattıktan sonra çocuğunuzun gerçek hayattaki ruh halini nasıl gözlemliyorsunuz?',
       'Çocuğunuzun oynadığı oyunlardaki yaş sınırı etiketlerini (Örn: PEGI 12, PEGI 18) kontrol ediyor musunuz?',
       'Türkiye'de yasal bir temsilcisi bulunmayan oyun platformlarına erişim kısıtlanması uygulanması ihtimalini nasıl değerlendiriyorsunuz?',
       'Sizlere daha iyi bir araştırma sunabilmek için dikkat ölçümü yapıyoruz. \n\nLütfen aşağıdaki seçenekler arasından 'Mavi' rengini işaretleyiniz.  ',
       'Sizlere daha iyi bir araştırma sunabilmek için dikkat ölçümü yapıyoruz. \n\nLütfen aşağıdaki seçenekler arasından 'Mavi' rengini işaretleyiniz.  ',
       'Oyun içinde gerçek parayla harcama YAPIYORSANIZ "en temel" amacı genellikle hangisidir?  ',
       'Çocuğunuz ortalama bir haftada, haftanın kaç günü oyun oynar?',
       'Ortalama bir haftayı düşündüğünüzde, haftanın kaç günü oyun oynarsınız?',
       '18 yaş altı kullanıcılar için oyun içi harcamalara ebeveyn onayı getirmeli midir?',
       '18 yaş altı kullanıcılar için oyun içi harcamalara ebeveyn onayı getirmeli midir?'],
      dtype='object')

In [ ]:
# SİSTEM RAPORU: Google Forms'dan gelen 39 adet ham sütun, 
# ML modellerine uygun 'snake_case' formatına çevriliyor.

yeni_kolonlar = [
    "zaman_damgasi",
    "anket_hedefi",                     # Bu anketi kimin adına dolduruyorsunuz?
    
    # --- OYUNCU (KENDİ ADINA) YANITLARI ---
    "oyuncu_cinsiyet",                  # Cinsiyetiniz?
    "oyuncu_yas",                       # Yaşınız?
    "oyuncu_gunluk_sure",               # Oyun oynadığınız günlerde süre...
    "oyuncu_cihaz",                     # EN SIK kullandığınız cihaz...
    "oyuncu_oyun_turu",                 # En çok vakit geçirdiğiniz oyun türü...
    "oyuncu_harcama_butcesi",           # Oyun içi harcamalara ayrılan bütçe...
    "oyuncu_harcama_etkisi",            # Oyun içi harcamalarınız bütçenizi...
    "oyuncu_maglubiyet_tepkisi",        # Rekabetçi bir maçı kaybettiğinizde...
    "oyuncu_motivasyon",                # EN TEMEL motivasyon nedir?
    "oyuncu_stres_etkisi",              # Genel stres seviyenizi nasıl etkiler?
    "oyuncu_uyku_feragati",             # Uykusuz kaldığınız ne sıklıkla olur?
    "oyuncu_ruh_hali",                  # Gerçek hayattaki ruh halinizi...
    "oyuncu_pegi_dikkat",               # Yaş sınırı (PEGI) uyarılarına...
    "oyuncu_platform_kisitlama_gorus",  # Erişim kısıtlanması ihtimalini...

    # --- VELİ VE ÇOCUK YANITLARI ---
    "veli_cinsiyet",                    # Cinsiyetiniz? (Veli formuna girenler için)
    "veli_yas",                         # Yaşınız? (Veli için)
    "cocuk_cinsiyet",                   # Çocuğunuzun Cinsiyeti?
    "cocuk_yas",                        # Çocuğunuzun yaşı?
    "cocuk_cihaz",                      # EN SIK kullandığı cihaz...
    "veli_ebeveyn_denetimi",            # Ebeveyn Denetimi kullanıyor musunuz?
    "cocuk_oyun_turu",                  # En çok vakit geçirdiği oyun türü...
    "cocuk_gunluk_sure",                # Genellikle toplam ne kadar süre...
    "veli_izin_verilen_harcama",        # İzin verilen oyun içi harcama...
    "veli_harcama_guven_etkisi",        # Bütçenizi ve aranızdaki güveni...
    "cocuk_kapatma_tepkisi",            # "Oyun süren bitti" dediğinizde tepkisi...
    "cocuk_stres_gozlemi",              # Genel stres ve kaygı seviyesi...
    "cocuk_uyku_gozlemi",               # Uyku düzeninin bozulduğunu...
    "cocuk_ruh_hali_gozlemi",           # Gerçek hayattaki ruh halini...
    "veli_pegi_kontrol",                # Yaş sınırı etiketlerini kontrol...
    "veli_platform_kisitlama_gorus",    # Erişim kısıtlanması ihtimalini (Veli)...

    # --- DİKKAT VE ORTAK SORULAR ---
    "dikkat_olcumu_1",                  # 'Mavi' rengini işaretleyiniz.
    "dikkat_olcumu_2",                  # 'Mavi' rengini işaretleyiniz. (Tekrarlı soru)
    "oyuncu_harcama_amaci",             # Harcama YAPIYORSANIZ en temel amacı...
    "cocuk_haftalik_oyun_gunu",         # Çocuğunuz haftanın kaç günü oyun oynar?
    "oyuncu_haftalik_oyun_gunu",        # Haftanın kaç günü oyun oynarsınız?
    "veli_ebeveyn_onay_gorus",        # Ebeveyn onayı getirmeli midir?
    "oyuncu_ebeveyn_onay_gorus"           # Ebeveyn onayı getirmeli midir? (Tekrarlı soru)
]

# Pandas'ın kolon isimlerini doğrudan kusursuz listemizle değiştiriyoruz
df.columns = yeni_kolonlar

# Başarı kontrolü için ilk 3 satırı ekrana basalım
print("✅ Kolon isimleri başarıyla 'snake_case' yapısına dönüştürüldü!")
display(df.head(3))

✅ Kolon isimleri başarıyla 'snake_case' yapısına dönüştürüldü!

,zaman_damgasi,anket_hedefi,oyuncu_cinsiyet,oyuncu_yas,oyuncu_gunluk_sure,oyuncu_cihaz,oyuncu_oyun_turu,oyuncu_harcama_butcesi,oyuncu_harcama_etkisi,oyuncu_maglubiyet_tepkisi,...,cocuk_ruh_hali_gozlemi,veli_pegi_kontrol,veli_platform_kisitlama_gorus,dikkat_olcumu_1,dikkat_olcumu_2,oyuncu_harcama_amaci,cocuk_haftalik_oyun_gunu,oyuncu_haftalik_oyun_gunu,veli_ebeveyn_onay_gorus,oyuncu_ebeveyn_onay_gorus
0,20.05.2026 20:12:33,18 Yaş Üzeriyim - Kendim İçin,Erkek,29-35,1-3 saat,"Kişisel Bilgisayar (Masaüstü, Laptop - Steam, ...","Rekabetçi Nişancı & Battle Royale (Valorant, C...",Hiç harcama yapmam,Hiç harcamam veya sınırlarımı asla aşmam.,Biraz moralim bozulur ama oyuna ara veririm.,...,,,,Mavi,,Oyun içi harcama yapmam.,,Neredeyse her gün / Her gün,,Kesinlikle destekliyorum
1,20.05.2026 20:14:01,18 Yaş Üzeriyim - Kendim İçin,Kadın,18-22,1-3 saat,"Mobil Cihaz (Akıllı Telefon, Tablet)","Strateji & MOBA (League of Legends - LoL, Clas...",250 TL'den az,Hiç harcamam veya sınırlarımı asla aşmam.,Hırslanırım ve mutlaka kazanana kadar peş peşe...,...,,,,Mavi,,"İçeriği belli olan, doğrudan istediğim bir eşy...",,Sıklıkla (Haftada 3-4 kez),,Kesinlikle destekliyorum
2,20.05.2026 20:26:50,18 Yaş Üzeriyim - Kendim İçin,Erkek,18-22,1-3 saat,"Mobil Cihaz (Akıllı Telefon, Tablet)","Basit Eğlence / Bulmaca (Candy Crush, Kelime O...",250 TL'den az,Hiç harcamam veya sınırlarımı asla aşmam.,Sakince oyunu kapatır veya başka bir işe geçerim.,...,,,,Mavi,,Oyun içi harcama yapmam.,,Hiçbir zaman,,Kesinlikle destekliyorum

In [ ]:
import numpy as np

# 1. ÖNCE TEMİZLİK: Google Sheets'in sahte boşluklarını ("") gerçek NaN değerine çeviriyoruz.
# regex=True sayesinde içinde sadece görünmez bir boşluk (" ") olan hatalı hücreler de yakalanır.
df = df.replace(r'^\s*$', np.nan, regex=True)

# 2. BÖLME İŞLEMİ VE SİLME (Şimdi dropna sorunsuz çalışacak)

# KOL 1: OYUNCULAR
df_oyuncular = df[df['anket_hedefi'] == '18 Yaş Üzeriyim - Kendim İçin'].copy()
df_oyuncular = df_oyuncular.dropna(axis=1, how='all')

# KOL 2: VELİLER
df_veliler = df[df['anket_hedefi'] == '18 Yaş Üzeriyim - Çocuğumun alışkanlıkları için'].copy()
df_veliler = df_veliler.dropna(axis=1, how='all')

# SİSTEM RAPORU
print(f"✅ BÖLÜNME VE SÜTUN TEMİZLİĞİ BAŞARILI!")
print(f"🎮 Oyuncu Tablosu: {len(df_oyuncular)} satır, {len(df_oyuncular.columns)} sütun")
print(f"👨‍👩‍👧 Veli Tablosu: {len(df_veliler)} satır, {len(df_veliler.columns)} sütun")

✅ BÖLÜNME VE SÜTUN TEMİZLİĞİ BAŞARILI!
🎮 Oyuncu Tablosu: 112 satır, 20 sütun
👨‍👩‍👧 Veli Tablosu: 23 satır, 21 sütun

In [ ]:
# Güvenlik filtresi fonksiyonumuz
def guvenlik_testi_uygula(veri):
    # İçinde 'dikkat_olcumu' geçen hayatta kalmış sütunları bul
    dikkat_sutunlari = [col for col in veri.columns if 'dikkat_olcumu' in col]
    
    if dikkat_sutunlari:
        # Sütunlardaki NaN değerleri boş string yapıp birleştiriyoruz
        # 'mavi' kelimesini (büyük/küçük harf duyarsız) arıyoruz
        sart = veri[dikkat_sutunlari].fillna('').astype(str).apply(
            lambda x: 'mavi' in ' '.join(x).lower(), axis=1
        )
        
        # Sadece testi geçenleri tut
        temiz_veri = veri[sart].copy()
        
        # Test bittiği için artık hiçbir işe yaramayan dikkat sütunlarını çöpe at (Feature Selection)
        temiz_veri = temiz_veri.drop(columns=dikkat_sutunlari)
        
        return temiz_veri
        
    return veri # Eğer dikkat sütunu hiç yoksa veriyi olduğu gibi döndür

# Filtreyi her iki tabloya da uyguluyoruz
df_oyuncular = guvenlik_testi_uygula(df_oyuncular)
df_veliler = guvenlik_testi_uygula(df_veliler)

# Son durumu raporlayalım
print("🛡️ GÜVENLİK FİLTRESİ UYGULANDI (Rastgele dolduranlar elendi ve dikkat sütunları silindi)")
print(f"🎮 Kalan Gerçek Oyuncu Sayısı: {len(df_oyuncular)}")
print(f"👨‍👩‍👧 Kalan Gerçek Veli Sayısı: {len(df_veliler)}")

🛡️ GÜVENLİK FİLTRESİ UYGULANDI (Rastgele dolduranlar elendi ve dikkat sütunları silindi)
🎮 Kalan Gerçek Oyuncu Sayısı: 111
👨‍👩‍👧 Kalan Gerçek Veli Sayısı: 22

In [ ]:
# ==========================================
# 🧹 EDA HEDEFLERİ VE VERİ TEMİZLİĞİ
# ==========================================

# ------------------------------------------
# 1. OYUNCULAR (df_oyuncular) İŞLEMLERİ
# ------------------------------------------

# Hedef 1: Gereksiz sütunları sil
silinecekler = ['zaman_damgasi', 'anket_hedefi']
df_oyuncular = df_oyuncular.drop(columns=silinecekler, errors='ignore')

# Hedef 2: 'Belirtmek İstemiyorum' diyenleri oyuncu_cinsiyet sütununun Mod'u ile doldur
if 'oyuncu_cinsiyet' in df_oyuncular.columns:
    # "Belirtmek İstemiyorum" haricindeki en çok geçen değeri (mod) bul
    oyuncu_mod = df_oyuncular[df_oyuncular['oyuncu_cinsiyet'] != 'Belirtmek İstemiyorum']['oyuncu_cinsiyet'].mode()[0]
    # Değişimi uygula
    df_oyuncular['oyuncu_cinsiyet'] = df_oyuncular['oyuncu_cinsiyet'].replace('Belirtmek İstemiyorum', oyuncu_mod)

# Hedef 3: oyuncu_harcama_amaci sütunundaki boş (NaN) değerleri doldur
if 'oyuncu_harcama_amaci' in df_oyuncular.columns:
    df_oyuncular['oyuncu_harcama_amaci'] = df_oyuncular['oyuncu_harcama_amaci'].fillna("Oyun içi harcama yapmam.")


# ------------------------------------------
# 2. VELİLER (df_veliler) İŞLEMLERİ
# ------------------------------------------

# Hedef 1: Gereksiz sütunları sil
df_veliler = df_veliler.drop(columns=silinecekler, errors='ignore')

# Hedef 2: veli_cinsiyet için 'Belirtmek İstemiyorum' olanları Mod ile doldur
if 'veli_cinsiyet' in df_veliler.columns:
    veli_mod = df_veliler[df_veliler['veli_cinsiyet'] != 'Belirtmek İstemiyorum']['veli_cinsiyet'].mode()[0]
    df_veliler['veli_cinsiyet'] = df_veliler['veli_cinsiyet'].replace('Belirtmek İstemiyorum', veli_mod)

# Hedef 3: cocuk_cinsiyet için 'Belirtmek İstemiyorum' olanları Mod ile doldur
if 'cocuk_cinsiyet' in df_veliler.columns:
    cocuk_mod = df_veliler[df_veliler['cocuk_cinsiyet'] != 'Belirtmek İstemiyorum']['cocuk_cinsiyet'].mode()[0]
    df_veliler['cocuk_cinsiyet'] = df_veliler['cocuk_cinsiyet'].replace('Belirtmek İstemiyorum', cocuk_mod)

# SİSTEM RAPORU
print("✅ EDA Temizlik Hedefleri Başarıyla Tamamlandı!")
print("-" * 40)
print(f"🎮 Oyuncu Tablosu Kalan Sütun Sayısı: {len(df_oyuncular.columns)}")
print(f"👨‍👩‍👧 Veli Tablosu Kalan Sütun Sayısı: {len(df_veliler.columns)}")

✅ EDA Temizlik Hedefleri Başarıyla Tamamlandı!
----------------------------------------
🎮 Oyuncu Tablosu Kalan Sütun Sayısı: 17
👨‍👩‍👧 Veli Tablosu Kalan Sütun Sayısı: 18

In [ ]:
def ardisik_tekrarlari_sil(df):
    # df.shift(1) veriyi bir satır aşağı kaydırır. 
    # Böylece her satırı doğrudan bir üstündeki satırla kıyaslamış oluruz.
    # all(axis=1) ise "Tüm sütunlar birebir aynı mı?" diye bakar.
    ardisik_mi = (df == df.shift(1)).all(axis=1)
    
    silinen_sayisi = ardisik_mi.sum()
    
    # Ardışık olmayan (True dönmeyen) temiz satırları tutuyoruz
    temiz_df = df[~ardisik_mi].copy()
    
    print(f"🧹 Ardışık Tekrar Kontrolü: {silinen_sayisi} adet çift tıklama (ardışık) kaydı silindi.")
    return temiz_df

# Fonksiyonu tablolarımıza uyguluyoruz
df_oyuncular = ardisik_tekrarlari_sil(df_oyuncular)
df_veliler = ardisik_tekrarlari_sil(df_veliler)

🧹 Ardışık Tekrar Kontrolü: 0 adet çift tıklama (ardışık) kaydı silindi.
🧹 Ardışık Tekrar Kontrolü: 0 adet çift tıklama (ardışık) kaydı silindi.

In [ ]:
# Kayıt yapacağımız klasörün var olduğundan emin olalım (Yosa otomatik açar)
hedef_klasor = '../data/processed'
os.makedirs(hedef_klasor, exist_ok=True)

# Verileri doğrudan ait oldukları işlenmiş veri klasörüne kaydediyoruz
df_oyuncular.to_csv(f'{hedef_klasor}/oyuncular_temiz.csv', index=False)
df_veliler.to_csv(f'{hedef_klasor}/veliler_temiz.csv', index=False)

print("💾 Veriler başarıyla 'data/processed' klasörüne kaydedildi!")

💾 Veriler başarıyla 'data/processed' klasörüne kaydedildi!

In [ ]:
display(df_veliler.head())

,veli_cinsiyet,veli_yas,cocuk_cinsiyet,cocuk_yas,cocuk_cihaz,veli_ebeveyn_denetimi,cocuk_oyun_turu,cocuk_gunluk_sure,veli_izin_verilen_harcama,veli_harcama_guven_etkisi,cocuk_kapatma_tepkisi,cocuk_stres_gozlemi,cocuk_uyku_gozlemi,cocuk_ruh_hali_gozlemi,veli_pegi_kontrol,veli_platform_kisitlama_gorus,cocuk_haftalik_oyun_gunu,veli_ebeveyn_onay_gorus
20,Kadın,18-22,Kız,10-13,"Mobil Cihaz (Akıllı Telefon, Tablet)","Evet, teknik ayarları (filtre, süre sınırı) ak...","Basit Eğlence / Bulmaca (Candy Crush, Kelime O...",1 saatten az,Hiç harcama yapmaz,Hiç harcamaz veya sadece izin verdiğimiz kadar...,"""Birazdan"", ""Son bir el"" diyerek süreyi esnetm...","Tamamen rahatlar, neşeli ve stressiz olur.",Hiçbir zaman,Hemen normal hayatına döner.,Evet her zaman,Kararsızım,Neredeyse her gün / Her gün,Kesinlikle destekliyorum
25,Kadın,36-45,Erkek,14-17,"Mobil Cihaz (Akıllı Telefon, Tablet)",Bu tür ayarların nasıl yapıldığını bilmiyorum.,"Hayatta Kalma, İnşa Etme & Sandbox (Minecraft,...",3-5 saat,250 TL'den az,Bazen limitini aşar ama bütçemizi sarsmaz.,"""Birazdan"", ""Son bir el"" diyerek süreyi esnetm...",Oynamadığı zamanlarda canı çabuk sıkılır veya ...,Sıklıkla (Haftada birkaç kez),O günkü genel morali düşer.,Hayır kontrol etmiyorum,Destekliyorum,Sıklıkla (Haftada 3-4 kez),Kesinlikle destekliyorum
28,Kadın,29-35,Kız,10-13,"Mobil Cihaz (Akıllı Telefon, Tablet)","Evet, teknik ayarları (filtre, süre sınırı) ak...","Basit Eğlence / Bulmaca (Candy Crush, Kelime O...",1-3 saat,250 TL'den az,Hiç harcamaz veya sadece izin verdiğimiz kadar...,"""Birazdan"", ""Son bir el"" diyerek süreyi esnetm...",Oynamadığı zamanlarda canı çabuk sıkılır veya ...,Nadiren (Ayda 1-2 kez),"Sadece anlık olarak canı sıkılır, çabuk geçer.",Bazen,Destekliyorum,Nadiren (Ayda 1-2 kez),Kesinlikle destekliyorum
35,Kadın,36-45,Kız,14-17,"Mobil Cihaz (Akıllı Telefon, Tablet)",Nasıl yapılacağını biliyorum ama uygulamıyorum.,"Hayatta Kalma, İnşa Etme & Sandbox (Minecraft,...",1 saatten az,Hiç harcama yapmaz,Hiç harcamaz veya sadece izin verdiğimiz kadar...,Söylendiği an sorunsuz kapatır.,Nötr (Oynaması veya oynamaması genel ruh halin...,Hiçbir zaman,Hemen normal hayatına döner.,Hayır kontrol etmiyorum,Destekliyorum,Sıklıkla (Haftada 3-4 kez),Destekliyorum
37,Kadın,36-45,Erkek,14-17,"Mobil Cihaz (Akıllı Telefon, Tablet)",Nasıl yapılacağını biliyorum ama uygulamıyorum.,"Hikaye Odaklı & Rol Yapma - RPG (The Witcher, ...",1-3 saat,Hiç harcama yapmaz,Hiç harcamaz veya sadece izin verdiğimiz kadar...,Söylendiği an sorunsuz kapatır.,Nötr (Oynaması veya oynamaması genel ruh halin...,Hiçbir zaman,Hemen normal hayatına döner.,Bazen,Kesinlikle destekliyorum,Bazen (Haftada 1-2 kez),Kesinlikle destekliyorum